# Generated by Django 5.2.7 on 2025-10-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='verPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ver_num', models.FloatField()),
                ('ver_text', models.TextField()),
                ('published_date', models.DateTimeField()),
            ],
        ),
    ]
