# Generated by Django 5.2.7 on 2025-11-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dl_package', '0002_verpost_created_date_alter_verpost_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verpost',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
