# Generated by Django 5.2.7 on 2025-11-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dl_package', '0003_alter_verpost_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='zipFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('upload', models.FileField(upload_to='games/')),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
