# Generated by Django 5.2.7 on 2025-11-12 21:29

import dl_package.models
import dl_package.storages
import dl_package.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dl_package', '0004_zipfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipfile',
            name='upload',
            field=models.FileField(storage=dl_package.storages.OverwriteStorage(), upload_to=dl_package.models.zip_upload_path, validators=[dl_package.validators.validate_is_zip]),
        ),
    ]
