# Generated by Django 5.2.7 on 2025-11-12 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dl_package', '0007_serialnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='serial_number',
        ),
    ]
